version: '3'
services:
  web:
    image: nginx
    hostname: web818
    container_name: web818
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "9818:80"
    restart: always
    depends_on:
      - php
    networks:
      - rts_818_net

  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: symfony:818-local
    restart: always
    hostname: php818
    container_name: php818
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
    networks:
      - rts_818_net

  db:
    image: postgres:14
    restart: always
    hostname: db818
    container_name: db818
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5818:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - rts_818_net

  pgdamin:
    image: dpage/pgadmin4
    hostname: pga818
    container_name: pga818
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGA_DEF_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGA_DEF_EMAIL}
    ports:
      - "10818:80"
    networks:
      - rts_818_net

volumes:
  db-data:

networks:
  rts_818_net:
    driver: bridge
