version: '3'
services:
  web:
    image: nginx
    hostname: web809
    container_name: web809
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "9809:80"
    restart: always
    depends_on:
      - php
    networks:
      - rts_809_net

  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: symfony:809-local
    restart: always
    hostname: php809
    container_name: php809
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
    networks:
      - rts_809_net

  db:
    image: postgres:14
    restart: always
    hostname: db809
    container_name: db809
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5809:5432"
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - rts_809_net

  pgdamin:
    image: dpage/pgadmin4
    hostname: pga809
    container_name: pga809
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGA_DEF_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGA_DEF_EMAIL}
    ports:
      - "10809:80"
    networks:
      - rts_809_net

networks:
  rts_809_net:
    driver: bridge
