version: '3'
services:
  web:
    image: nginx
    hostname: web743
    container_name: web743
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "9743:80"
    restart: always
    depends_on:
      - php
    networks:
      - rts_743_net

  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: symfony:743-local
    restart: always
    hostname: php743
    container_name: php743
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
    networks:
      - rts_743_net

  db:
    image: postgres:14
    restart: always
    hostname: db743
    container_name: db743
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5743:5432"
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - rts_743_net

  pgdamin:
    image: dpage/pgadmin4
    hostname: pga743
    container_name: pga743
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGA_DEF_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGA_DEF_EMAIL}
    ports:
      - "10743:80"
    networks:
      - rts_743_net

networks:
  rts_743_net:
    driver: bridge
